feat: Criar método ver brindes na classe cliente
erikabusiness/koru-mobile-projeto-3 pull request #33
Opened 2024-04-12 20:17 UTC by franbs2

## Objetivo da tarefa
verBrindes (retorno: void):
- Método responsável realizar um print dos brindes recebidos em ordem alfabética.
- Exemplo:
> “Brindes recebidos por Maria: Colônia Egeo 10ml Aromatizador de ambientes

## O que foi feito
- Criado o método ver brindes.
- Foi chamado o método na main.

2024-04-14 21:00 UTC, vsjhonny approved these changes

2024-04-15 22:11 UTC, jcr04 approved these changes

2024-04-16 23:02 UTC, lolaleid approved these changes
Sugiro desativar a opção de auto-formatação do vscode para gerar menos alterações no commit e consequentemente menos conflitos.

2024-04-17 12:27 UTC, jaquedreyer requested changes

2024-04-17 12:27 UTC, jaquedreyer commented on classes/cliente.dart
> +    ordenarBrinde();
```suggestion
    ordenarBrindes();
```

2024-04-17 17:28 UTC, franbs2 commented on classes/cliente.dart
> +    ordenarBrinde();
Obrigada pelo aviso, Jaque! Não havia notado.

2024-04-17 18:06 UTC, jaquedreyer approved these changes
Boa, Fran!

2024-04-17 20:03 UTC, merged