feat: método para calcular o lucro do revendedor
erikabusiness/koru-mobile-projeto-3 pull request #35
Opened 2024-04-14 00:43 UTC by erikabusiness

## Objetivo da tarefa

- Criar o método `calcularLucro`  com retorno: double que será responsável por calcular e retornar o lucro em reais obtido por aquele revendedor utilizando o dado de porcentagem de lucro daquele vendedor.

## O que foi feito
- Criei o método calcularLucro na classe Revendedor.
- Chamada para o método na main.

2024-04-14 20:59 UTC, vsjhonny approved these changes

2024-04-17 00:17 UTC, lolaleid requested changes
Nesse caso o forEach é um método interessante de se resolver. Outra forma, seria apenas multiplicando o total vendido pela porcentagem de lucro, o resultado seria o mesmo, pois a porcentagem de lucro é a mesma para todos os produtos.

2024-04-17 00:17 UTC, lolaleid commented on classes/revendedor.dart
> +    double totalVendas = 85.80;
```suggestion
    double totalVendas = calcularTotalVendido();
```

2024-04-18 22:26 UTC, lolaleid approved these changes

2024-04-18 22:29 UTC, lolaleid commented on classes/revendedor.dart
> +    });
Como você puxou o valor do total vendido, pode remover essas linhas, pois fica redundante o cálculo do total vendido.

```suggestion
  
```

2024-04-18 22:35 UTC, lolaleid approved these changes
Parabéns! Aprovado. 🚀

2024-04-18 22:54 UTC, jaquedreyer approved these changes

2024-04-18 23:21 UTC, merged