feat: método produtos comprados
erikabusiness/koru-mobile-projeto-3 pull request #39
Opened 2024-04-14 04:26 UTC by erikabusiness

## Objetivo da tarefa

- Criar método ´verProdutosComprados()´ responsável realizar um print dos produtos comprados em ordem alfabética, juntamente com os seus valores e sem retorno.

## O que foi feito
- Criei o método ´verProdutosComprados()´ responsável realizar um print dos produtos comprados em ordem alfabética, juntamente com os seus valores e sem retorno onde primeiro verifico se tem produtos comprados, depois prossigo com a validação de ordem alfabetica dos nomes dos produtos e imprimo na tela os itens comprados.

2024-04-14 20:58 UTC, vsjhonny approved these changes

2024-04-15 22:06 UTC, jcr04 approved these changes

2024-04-16 18:12 UTC, jaquedreyer requested changes

2024-04-18 22:36 UTC, lolaleid commented on classes/cliente.dart
> +      ordenarProdutosComprados ()
```suggestion
      ordenarProdutosComprados ();
```

2024-04-18 22:45 UTC, jaquedreyer approved these changes

2024-04-18 23:21 UTC, merged