Feact: Refactor Produto
erikabusiness/koru-mobile-projeto-3 pull request #55
Opened 2024-04-20 22:43 UTC by kamilateofilo

## Objetivo da tarefa
 Refatoração da classe produto.

## O que foi feito
-  Mantive o padrão de nomenclatura dos métodos e variáveis, 
- Adicionei chaves em torno dos blocos de código dos métodos realizarVenda e verReceitaGerada para garantir clareza
- Adicionei espaçamento vertical entre os métodos e seções de código para melhorar a legibilidade do código.
- Removi comentários redundantes que apenas repetiam o que já estava claro no código.

2024-04-21 21:42 UTC, franbs2 approved these changes
Aprovado!

2024-04-21 21:47 UTC, jaquedreyer commented on classes/produto.dart
> +  // Construtor
```suggestion
```

2024-04-21 21:51 UTC, jaquedreyer requested changes

2024-04-21 21:51 UTC, jaquedreyer commented on classes/produto.dart
> +  // Construtor
```suggestion
```

2024-04-21 21:51 UTC, jaquedreyer commented on classes/produto.dart
> +  // Construtor
Pensando em melhorias, esse comentário poderia ser excluído, não é necessário para o entendimento do código.

2024-04-22 10:30 UTC, jaquedreyer approved these changes

2024-04-22 11:51 UTC, merged